AWSTemplateFormatVersion: '2010-09-09'
Description: A template for a Lambda function and an API Gateway with CORS.

Resources:
  TwoSumLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler # assuming the handler function is named 'handler' in 'index.js'
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8 # specify your runtime environment
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              # Your 2-sum code here
              return {
                  "statusCode": 200,
                  "body": json.dumps({"message": "Hello World"})
              }

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*

  TwoSumApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: TwoSumApi
      Description: API for 2-sum Lambda function
      FailOnWarnings: 'true'

  LambdaApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref TwoSumApi
      ParentId: !GetAtt TwoSumApi.RootResourceId
      PathPart: twosum # the path where the API is deployed

  LambdaMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TwoSumApi
      ResourceId: !Ref LambdaApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TwoSumLambda.Arn}/invocations

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TwoSumLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TwoSumApi}/*/*

  CorsOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref TwoSumApi
      ResourceId: !Ref LambdaApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: "{\"statusCode\": 200}"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
